### ISSUE TITLE
How to find current requester's id

### ISSUE THREAD

**Issue by mrvahedi68** [pondersource/mfaverifiedzone#2]
I want to find the current requester (User) id.
Currently used this approach:

https://github.com/pondersource/mfaverifiedzone/blob/842ce99cb413286870b0c877a9d0346feec022fa/lib/Controller/MfaVerifiedZoneController.php#L65

It returns only 'Admin'. Now, I must find out if this user is the owner of the file or not.

**Comment by michielbdejong** [comment]
I think you can just add `$userId` as a constructor argument and then DI will fill it in; can you try out if that works?

**Comment by mrvahedi68** [comment]
Fixed on 71915d36eee9a5424da4f79f7da4bb5f8a817c2f
